//----------------------------------------------------------------------------------

//RandomMomOnSphere.cc
//Written by Andrew Boldy
//University of South Carolina
//Spring 2026

//----------------------------------------------------------------------------------
//This is the .cc code fo rthe RandomMomOnSphere class
//Definition of member functions for three different instances of the fire() function for production of a three vector at a given momentum
//There are swithces that are being used for the sake of debugging and different functionality that can be expanded in the future

//Switches of import:
//B2B: tells the code whether or not to produce a back to back set of vectors. Most basic code (need to make sure that if false there are checks in debug to ensure this is truly the case)
//DIFFMAG: tells the code if the two momenta being simulated are meant to be at different magnitudes. Useful mostly for processes that have differing masses
//DEBUG: tells the code whether or not to print a set of debug outputs to the console for the purpose of identifying bugs
//----------------------------------------------------------------------------------

//================================================================
// Inclusions
//================================================================

//Corresponding Header
#include "RandomMomOnSphere.hh"

//Standard Inclusions
#include <iostream>

//Fermilab General or Mu2e Inclusions
#include "Offline/Mu2eUtilities/inc/ThreeVectorUtil.hh"
#include "Offline/GeneralUtilities/inc/safeSqrt.hh"
#include "Offline/GeneralUtilities/inc/sqrtOrThrow.hh"

using threeVec = CLHEP::Hep3Vector;
using CLHEP::RandFlat;
using CLHEP::HepRandomEngine;
using std::pair;

namespace mu2e
{
  //================================================================
  // Constructors
  //================================================================
  RandomMomOnSphere::RandomMomOnSphere(HepRandomEngine& engine, double cMin, double cMax, double pMin, double pMax):
    _czMin(cMin),
    _czMax(cMax),
    _phiMin(pMin),
    _phiMax(pMax),
    _randFlat(engine) {}

  RandomMomOnSphere::RandomMomOnSphere(HepRandomEngine& engine, const RandomMomOnSphereParams& params):
    _czMin(params.czMin),
    _czMax(params.czMax),
    _phiMin(params.phiMin),
    _phiMax(params.phiMax),
    _randFlat(engine) {}


  //================================================================
  // Function Definitions
  //================================================================

  //fire()
  threeVec RandomMomOnSphere::fire()
  {
    double cz = _czMin + (_czMax - _czMin)*_randFlat.fire(); //chooses a value for the cosine of theta generated by the random flat distribution in CLHEP
    double phi = _phiMin + (_phiMax - _phiMin)*_randFlat.fire(); //chooses a value for phi generated by the random flat distribution in CLHEP

    double sz = safeSqrt(1.-cz*cz); //produce the sine of theta from the cosine of theta

    double x = sz*cos(phi); //produces the x coordinate for the Hep3Vector in accordance with the structure that is published
    double y = sz*sin(phi); //produces the y coordinate for the Hep3Vector in accordance with the structure that is published
    double z = cz; //produces the z coordinate for the Hep3Vector in accordance with the structure that is published
    threeVec threeUnit = threeVec(x, y, z); //creates the three vector (unit vector)
    return threeUnit; //return the unit vector
  } //end fire() function definition

  //fire(double mag)
  threeVec RandomMomOnSphere::fire(double mag)
  {
    return mag*fire();
  } //end fire(double mag) function definition

  //fire_pair(double mag1, double mag2) (if wanting to do angular distributions in here, can setup a distribution structure that will allow to be taken in)
  pair<threeVec, threeVec> RandomMomOnSphere::fire_pair(double mag1, double mag2, bool B2B, bool DIFFMAG, bool DEBUG)
  {
    if (DIFFMAG == false)
    {
      if (B2B == true)
      {
        threeVec vec1 = mag1*fire();
        threeVec vec2 = -vec1;
        if (DEBUG == true)
        {
          //Checking values for debug
          std::cout << "Printing debug data and histograms for event." << std::endl;
          std::cout << "Vector 1 Linear Data: Vec1x = " << vec1.x() << ", Vec1y = " << vec1.y() << ", Vec1z = " << vec1.z() << ", Vec1 Magnitude = " << vec1.mag() << std::endl;
          std::cout << "Vector 1 Spherical Data: Vec1 Magnitude = " << vec1.mag() << ", Vec1 Theta = " << vec1.theta() << ", Vec1 cos(Theta) = " << vec1.cosTheta() << ", Vec1 Phi= " << vec1.phi() << std::endl;
          std::cout << "Vec2x = " << vec2.x() << ", Vec2y = " << vec2.y() << ", Vec2z = " << vec2.z() << ", Vec2 Magnitude = " << vec2.mag() << std::endl;
          std::cout << "Vector 2 Spherical Data: Vec2 Magnitude = " << vec2.mag() << ", Vec2 Theta = " << vec2.theta() << ", Vec2 cos(Theta) = " << vec2.cosTheta() << ", Vec2 Phi= " << vec2.phi() << std::endl;

          //Checking specific error conditions
          if (vec1.mag() != vec2.mag()) //magnitude mismatch error
          {
            std::cerr << "Magnitudes of vector do not match. Please check switches to ensure you have stated the correct boolean for DIFFMAG." << std::endl;
          } //end debug check on magnitude mismatch
          else {std::cout << "Magnitudes match!" << std::endl;}

          if (vec1.x() == vec2.x() && vec1.y() == vec2.y() && vec1.z() == vec2.z()) //same vector error
          {
            std::cerr << "Vectors are the same." << std::endl;
          } //end debug check on same vector
          else {std::cout << "Vectors differ in at least one coordinate!" << std::endl;}
        } //end debug switch for DIFFMAG = false and B2B = true
        return {vec1,vec2};
      } //end B2B true condition for back to back

      else if (B2B == false)
      {
        throw std::runtime_error("ERROR: Angular Distribution has not yet been setup. Please contact developer if intending to use.");
      } //end B2B false condition

      else
      {
        throw std::runtime_error("ERROR: Unknown entry for back to back boolean.");
      } //end B2B unknown condition
    } //end the DIFFMAG false condition

    else if (DIFFMAG == true)
    {
      throw std::runtime_error("ERROR: Difference in magnitude of vectors has not been setup. Please contact developer if intending to use.");
    } //end DIFFMAG true condition

    else
    {
      throw std::runtime_error("ERROR: Unknown entry for difference in magnitude of thrown vector boolean.");
    } //end DIFFMAG unknown condition
  }//end fire(double mag1, double mag2) function definition


} //end namespace mu2e
